apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    resource.kubernetes.io/admin-access: "true"
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
