# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: qbittorrent-secret
    template:
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .PROTONVPN_WIREGUARD_PRIVATE_KEY }}"
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .GLUETUN_API_KEY }}"
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
  data:
    - secretKey: PROTONVPN_WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: /Kubernetes/DexTek/VPN/PROTONVPN_WIREGUARD_PRIVATE_KEY
    - secretKey: GLUETUN_API_KEY
      remoteRef:
        key: /Kubernetes/DexTek/VPN/GLUETUN_API_KEY
