---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/docker
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/ghcr
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: gcr.io
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/gcr
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: quay.io
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/quay
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: mcr.microsoft.com
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/mcr
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: public.ecr.aws
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/ecr
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/k8s
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: mirror.gcr.io
endpoints:
  - url: https://zot.fast.plexuz.xyz/v2/mirror-gcr
    overridePath: true
skipFallback: true
