---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cnpg-secrets
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        host: "postgres-rw.databases.svc"
        database: "${APP}"
        sslmode: "${DATABASE_SSLMODE:=require}"
        url: "postgresql://{{ .username }}:{{ .password }}@postgres-rw.databases.svc/${APP}?sslmode=${DATABASE_SSLMODE:=require}"
  data:
    - secretKey: username
      remoteRef:
        key: ${APP}-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: ${APP}-postgres
        property: password
