---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-postgres
spec:
  refreshInterval: "0"
  target:
    name: *name
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "databases"
        labels:
          cnpg.io/reload: "true"
      data:
        username: "${DATABASE_OWNER:=${APP}}"
        password: "{{ .password }}"
        host: "postgres-rw.databases.svc"
        database: "${APP}"
        url: "postgresql://${DATABASE_OWNER:=${APP}}:{{ .password }}@postgres-rw.databases.svc/${APP}?sslmode=disable"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
