---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./externalsecret.yaml
  - ./ks-password.yaml
  - ../base/ks.yaml
patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      version: v1
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: not-used
      spec:
        postBuild:
          substitute:
            DISABLE_PASSWORD: "false"
            APP: "${APP}"
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.ksgate.org/postgres-ready: |
                {
                  "apiVersion": "postgresql.cnpg.io/v1",
                  "kind": "Cluster",
                  "name": "postgres",
                  "namespace": "databases",
                  "expression": "resource.status.readyInstances >= 1"
                }
              k8s.ksgate.org/postgres-service: |
                {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "name": "pooler-rw",
                  "namespace": "databases"
                }
              k8s.ksgate.org/database-applied: |
                {
                  "apiVersion": "postgresql.cnpg.io/v1",
                  "kind": "Database",
                  "name": "${APP}",
                  "namespace": "databases",
                  "expression": "resource.status.applied"
                }
            schedulingGates:
              - name: k8s.ksgate.org/postgres-ready
              - name: k8s.ksgate.org/postgres-service
              - name: k8s.ksgate.org/database-applied
