---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
  namespace: downloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: qui-secret
    template:
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
        QUI__OIDC_CLIENT_ID: "{{ .QUI_OAUTH_CLIENT_ID }}"
        QUI__OIDC_CLIENT_SECRET: "{{ .QUI_OAUTH_CLIENT_SECRET }}"
  data:
    - secretKey: QUI_SESSION_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Qui/QUI_SESSION_SECRET
    - secretKey: QUI_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Qui/QUI_OAUTH_CLIENT_ID
    - secretKey: QUI_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Qui/QUI_OAUTH_CLIENT_SECRET
