---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redbot
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: redbot
  values:
    controllers:
      app:
        pod:
          hostUsers: false
        containers:
          app:
            image:
              repository: phasecorex/red-discordbot
              tag: extra-audio-py311@sha256:02a8c79810760520a3dd7b213a1ad4600414bdb3a50f68f2fc08156976d4336b
            env:
              PUID: 568
              PGID: 568
            envFrom:
              - secretRef:
                  name: redbot-secret
            resources:
              requests:
                cpu: 50m
                memory: 400M
              limits:
                memory: 843M
    persistence:
      config:
        existingClaim: redbot-config
        globalMounts:
          - path: /data
