---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: flux-webhook-token
    template:
      data:
        token: "{{ .FLUX_WEBHOOK_TOKEN }}"
  data:
    - secretKey: FLUX_WEBHOOK_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Flux/FLUX_WEBHOOK_TOKEN
