---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-icons
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gotify-icons-secret
  data:
    - secretKey: GOTIFY_USERNAME
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_DEFAULTUSER_NAME
    - secretKey: GOTIFY_PASSWORD
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_DEFAULTUSER_NAME
