---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../base/patch
resources:
  - ../base/ks.yaml
  - ./certificate.yaml
  - ./secret.yaml
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          persistence:
            postgres-certs:
              type: secret
              name: "{{ .Release.Name }}-postgres-cert"
              defaultMode: 0600
              globalMounts:
                - path: /var/run/secrets/postgresql
            root-ca:
              type: secret
              name: root-ca
              defaultMode: 0440
              globalMounts:
                - path: /var/run/secrets/root-ca