---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: jellyfin-config-secret
    template:
      data:
        JELLARR_API_KEY: "{{ .JELLARR_API_KEY }}"
        config.yml: |
          version: 1
          base_url: http://jellyfin.default.svc.cluster.local:8096
          system: {}
          plugins:
            - name: LDAP-Auth
              configuration:
                LdapServer: ak-outpost-ldap.auth.svc.cluster.local
                LdapPort: 636
                UseSsl: true
                UseStartTls: false
                SkipSslVerify: true
                LdapBindUser: cn=ldap_bind,ou=users,dc=ldap,dc=dextek,dc=io
                LdapBindPassword: "{{ .LDAP_BIND_PASSWORD }}"
                LdapBaseDn: ou=users,dc=ldap,dc=dextek,dc=io
                LdapSearchFilter: "(memberOf=cn=jellyfin-users,ou=groups,dc=ldap,dc=dextek,dc=io)"
                LdapAdminBaseDn: ""
                LdapAdminFilter: "(memberOf=cn=jellyfin-admins,ou=groups,dc=ldap,dc=dextek,dc=io)"
                EnableLdapAdminFilterMemberUid: false
                LdapSearchAttributes: uid, cn, mail, displayName
                LdapClientCertPath: ""
                LdapClientKeyPath: ""
                LdapRootCaPath: ""
                CreateUsersFromLdap: true
                AllowPassChange: false
                LdapUidAttribute: uid
                LdapUsernameAttribute: cn
                LdapPasswordAttribute: userPassword
                EnableLdapProfileImageSync: true
                RemoveImagesNotInLdap: true
                LdapProfileImageAttribute: jpegphoto
                LdapProfileImageFormat: Url
                EnableAllFolders: false
                EnabledFolders:
                  - f137a2dd21bbc1b99aa5c0f6bf02a805 # Movies
                  - a656b907eb3a73532e40e44b968d0225 # Shows
                PasswordResetUrl: ""
  data:
    - secretKey: JELLARR_API_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Jellyfin/JELLYFIN_API_KEY
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: /Kubernetes/DexTek/Authentik/AUTHENTIK_LDAP_BIND_PASSWORD
