---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-config
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: jellyfin-config
  values:
    controllers:
      jellyfin-config:
        annotations:
          reloader.stakater.com/auto: "true"
        type: cronjob
        cronjob:
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        containers:
          app:
            image:
              repository: ghcr.io/venkyr77/jellarr
              tag: v0.1.0
            envFrom:
              - secretRef:
                  name: jellyfin-config-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512M
        pod:
          hostUsers: false
          restartPolicy: Never
    persistence:
      tmp:
        type: emptyDir
        medium: Memory
      config:
        type: secret
        name: jellyfin-config-secret
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
