---
keys:
  - &user_krezh age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
  - &user_krezh_yubikey age1yubikey1q2uwxvgqn5c6gx3qlgvj8dg20ev4s4gjgz4gddut6sdy82knvtwdqhdar4a
  - &user_flux age15e7zt8gwt8eg2hcm35h0mlvvexkrxj8uu424lvrmlzvma3ancpvslcevcg

creation_rules:
  - path_regex: ^[^.].*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_krezh
          - *user_flux
          - *user_krezh_yubikey
