---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifier
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: notifier-secret
    template:
      data:
        APPRISE_RADARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .RADARR_PUSHOVER_TOKEN }}
        APPRISE_SEERR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .SEERR_PUSHOVER_TOKEN }}
        APPRISE_SONARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .SONARR_PUSHOVER_TOKEN }}
  dataFrom:
    - find:
        path: /Kubernetes/DexTek/Sonarr
        name:
          regexp: "(.*)"
    - find:
        path: /Kubernetes/DexTek/Radarr
        name:
          regexp: "(.*)"
    - find:
        path: /Kubernetes/DexTek/Jellyseerr
        name:
          regexp: "(.*)"
    - find:
        path: /Kubernetes/DexTek/Pushover
        name:
          regexp: "(.*)"
