---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gotify-secret
    template:
      data:
        GOTIFY_DEFAULTUSER_NAME: "{{ .GOTIFY_DEFAULTUSER_NAME }}"
        GOTIFY_DEFAULTUSER_PASS: "{{ .GOTIFY_DEFAULTUSER_PASS }}"
        GOTIFY_OIDC_CLIENTID: "{{ .GOTIFY_OAUTH_CLIENT_ID }}"
        GOTIFY_OIDC_CLIENTSECRET: "{{ .GOTIFY_OAUTH_CLIENT_SECRET }}"
  data:
    - secretKey: GOTIFY_DEFAULTUSER_NAME
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_DEFAULTUSER_NAME
    - secretKey: GOTIFY_DEFAULTUSER_PASS
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_DEFAULTUSER_PASS
    - secretKey: GOTIFY_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_OAUTH_CLIENT_ID
    - secretKey: GOTIFY_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_OAUTH_CLIENT_SECRET
