---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gotify-secret
    template:
      data:
        GOTIFY_DEFAULTUSER_NAME: "{{ .GOTIFY_DEFAULTUSER_NAME }}"
        GOTIFY_DEFAULTUSER_PASS: "{{ .GOTIFY_DEFAULTUSER_PASS }}"
        GOTIFY_DATABASE_CONNECTION: |-
          host='{{ .host }}' port='{{ .port }}' user='{{ .user }}' dbname='{{ .dbname }}' password='{{ .password }}'
  data:
    - secretKey: GOTIFY_DEFAULTUSER_NAME
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_DEFAULTUSER_NAME
    - secretKey: GOTIFY_DEFAULTUSER_PASS
      remoteRef:
        key: /Kubernetes/DexTek/Gotify/GOTIFY_DEFAULTUSER_PASS
  dataFrom:
    - extract:
        key: postgres-pguser-gotify
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
