---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel
spec:
  endpoints:
    - dnsName: ingress-ext.plexuz.xyz
      recordType: A
      targets:
        - 62.238.2.224
    - dnsName: twnl.plexuz.xyz
      recordType: CNAME
      targets:
        - ingress-ext.plexuz.xyz
    - dnsName: tunnel.plexuz.xyz
      recordType: CNAME
      targets:
        - ingress-ext.plexuz.xyz
