---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-image-renderer
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: grafana-image-renderer
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      renderer:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/grafana/grafana-image-renderer
              tag: v5.12.1@sha256:e925ba95a07372527cd79827381f83f3fe7895511ee46508e35fd9400b56a369
            env:
              AUTH_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: grafana-image-renderer
                    key: token
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: renderer
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
            path: /metrics
    persistence:
      home:
        type: emptyDir
        globalMounts:
          - path: /home/nonroot
      shared-memory:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /dev/shm
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
