---
name: "Publish Terraform"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["infrastructure/terraform/**", "clusters/**/terraform/**"]

jobs:
  publish-infrastructure:
    name: Publish Infrastructure
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: "${{ github.token }}"
          persist-credentials: false

      - name: Setup Flux CLI
        shell: bash
        run: curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Set registry host
        id: registry
        shell: bash
        run: echo "host=$(echo '${{ github.server_url }}' | sed 's|https://||' | sed 's|http://||')" >> "${GITHUB_OUTPUT}"

      - name: Login to Forgejo Container Registry
        shell: bash
        run: echo "${{ github.token }}" | docker login "${{ steps.registry.outputs.host }}" -u "${{ github.actor }}" --password-stdin

      - name: Generate tag
        id: generate-tag
        shell: bash
        run: echo "tag=${{ steps.registry.outputs.host }}/${{ github.repository }}/manifests/infrastructure:$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Publish manifests
        shell: bash
        env:
          OCI_TAG: ${{ steps.generate-tag.outputs.tag }}
        run: |
          mkdir /tmp/terraform
          cp -r infrastructure/terraform/* /tmp/terraform
          for tf_dir in clusters/*/terraform/*; do
            cluster_name=$(basename "$(dirname "$(dirname "$tf_dir")")")
            terraform_folder_name=$(basename "$tf_dir")
            dest_dir="/tmp/terraform/${cluster_name}/${terraform_folder_name}"
            mkdir -p "$dest_dir"
            cp -r "$tf_dir"/* "$dest_dir"/
          done
          ls /tmp/terraform
          flux push artifact oci://$OCI_TAG \
              --path="/tmp/terraform" \
              --source="$(git config --get remote.origin.url)" \
              --revision="$(git branch --show-current)/$(git rev-parse HEAD)"

      - name: Tag manifests
        shell: bash
        env:
          OCI_TAG: ${{ steps.generate-tag.outputs.tag }}
        run: flux tag artifact oci://$OCI_TAG --tag main
