---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: termix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: termix-secret
    template:
      data:
        OIDC_CLIENT_ID: "{{ .TERMIX_OAUTH_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .TERMIX_OAUTH_CLIENT_SECRET }}"
  data:
    - secretKey: TERMIX_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Termix/TERMIX_OAUTH_CLIENT_ID
    - secretKey: TERMIX_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Termix/TERMIX_OAUTH_CLIENT_SECRET
