---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app termix
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: termix
  values:
    controllers:
      termix:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          termix:
            image:
              repository: ghcr.io/lukegus/termix
              tag: release-2.1.0
            env:
              PORT: &port 8080
              OIDC_IDENTIFIER_PATH: "sub"
              OIDC_NAME_PATH: "name"
              OIDC_SCOPES: "openid profile email"
              OIDC_ISSUER_URL: "https://sso.plexuz.xyz/application/o/termix/"
              OIDC_AUTHORIZATION_URL: "https://sso.plexuz.xyz/application/o/authorize/"
              OIDC_TOKEN_URL: "https://sso.plexuz.xyz/application/o/token/"
              OIDC_USERINFO_URL: "https://sso.plexuz.xyz/application/o/userinfo/"
            envFrom:
              - secretRef:
                  name: termix-secret
            resources:
              requests:
                cpu: 100m
                memory: 256M
              limits:
                memory: 512M
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      termix:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["termix.talos.plexuz.xyz"]
        parentRefs:
          - name: gateway-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      data:
        enabled: true
        existingClaim: termix-config
        globalMounts:
          - path: /app/data
