---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-db
  namespace: &namespace databases
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: flux-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      name: ${APP}
      namespace: *namespace
  interval: 1h
  path: ./clusters/shared/components/cnpg/base/database
  postBuild:
    substitute:
      APP: ${APP}
      OWNER: ${DATABASE_OWNER:=${APP}}
      EXTENSIONS: ${q:='}${DATABASE_EXTENSIONS}${q:='}
      DATABASE_SUPERUSER: ${q:='}${DATABASE_SUPERUSER:=false}${q:='}
      DISABLE_PASSWORD: ${q:='}${DISABLE_PASSWORD:=true}${q:='}
      emptyArray: "[]"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
