---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentmemory
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: agentmemory-secret
    template:
      data:
        AGENTMEMORY_SECRET: "{{ .AGENTMEMORY_SECRET }}"
  data:
    - secretKey: AGENTMEMORY_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/AgentMemory/AGENTMEMORY_SECRET
