---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: miniflux-secret
    template:
      data:
        # App
        ADMIN_USERNAME: "{{ .MINIFLUX_ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .MINIFLUX_ADMIN_PASSWORD }}"
        DATABASE_URL: '{{ index . "uri" }}'
        OAUTH2_CLIENT_ID: "{{ .MINIFLUX_OAUTH_CLIENT_ID }}"
        OAUTH2_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}"
        OAUTH2_USER_CREATION: "1"
        OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://sso.plexuz.xyz/application/o/miniflux/.well-known/openid-configuration"
        OAUTH2_PROVIDER: oidc
        OAUTH2_REDIRECT_URL: "https://miniflux.plexuz.xyz/oauth2/oidc/callback"
  data:
    - secretKey: MINIFLUX_ADMIN_USERNAME
      remoteRef:
        key: /Kubernetes/DexTek/Miniflux/MINIFLUX_ADMIN_USERNAME
    - secretKey: MINIFLUX_ADMIN_PASSWORD
      remoteRef:
        key: /Kubernetes/DexTek/Miniflux/MINIFLUX_ADMIN_PASSWORD
    - secretKey: MINIFLUX_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Miniflux/MINIFLUX_OAUTH_CLIENT_ID
    - secretKey: MINIFLUX_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Miniflux/MINIFLUX_OAUTH_CLIENT_SECRET
  dataFrom:
    - extract:
        key: postgres-pguser-miniflux
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
