---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/restore_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: ${APP}
spec:
  mover:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      capabilities:
        add:
          - DAC_OVERRIDE
          - CHOWN
          - FOWNER
        drop:
          - ALL
    privilegedMode: true # preserves original UID/GID ownership on restore
  options:
    parallel: 20
  policy:
    onMissingSnapshot: Continue
  source:
    fromPolicy:
      name: ${APP}
      offset: 0
  target:
    populator: {}
