apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:N6k0spxWHkE=,iv:A47pqzYpMsqBMsK/34TOLekOvob5FmfQXloBGPCNZdc=,tag:9/G390WUm6FLuqp2NXNTpw==,type:comment]
    SECRET_EMAIL: ENC[AES256_GCM,data:TlBwCNpeg6AGgEU=,iv:+WPlq8x9sb0eRu8XbED7DHftgkHbXyQxZc3zkA91Fl4=,tag:reZFrfr+VdCrbZ5v7oULAA==,type:str]
    #ENC[AES256_GCM,data:wUXtlBFfSxK8EqLZFjqx,iv:4RdJI7BcCDZBxndMJylp5mpqL8cUg0plPIHyt/8W7f8=,tag:kBe319VR0OkbBAA7dyvSPg==,type:comment]
    SECRET_RPI01_FQDN: ENC[AES256_GCM,data:su159HhLjoNLs5w63S9o9QrLx6E=,iv:Kt1iZeszzkDgRpz0hkNiez5V6+g2/WpQApYWo6fX+zg=,tag:k1RhZKLWkZ4fRx04aBPMeg==,type:str]
    SECRET_RPI02_FQDN: ENC[AES256_GCM,data:vZ0IxWvEPDZ3h97Ocm9GGhiX+6g=,iv:6XtRHQ6/QH7C/pFKUigTUK7rhE1CBdM3kYpcqmta/Iw=,tag:Mu4wOOehZ5c7ZjphWtuFuw==,type:str]
sops:
    age:
        - recipient: age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbVJhbi9yVGJsNngyQWE0
            R3U2KzFyRk4rMjlXRnFWRUIySEp1SWJqVHl3Cm5zQ3VpZGxnZnVSV2FGOExqdk5h
            azJ1dThGZFg1VThLQ3ZDVGNYOURMbTgKLS0tIGs0UjcrUHBJY0NyQ2FaMVU2NFhj
            R2NsZnFCUnB1OEpySDVMcGt2WlFKUUEKTRPKa3xmjDR/btkMFU5UuuNc1KJpgRLe
            OW12MxyX6uVy41yxhUq2vIENwuSWzaW/RWktbAwtK27EEb9nWwOnXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e7zt8gwt8eg2hcm35h0mlvvexkrxj8uu424lvrmlzvma3ancpvslcevcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbUM0RmJPUUhZbC9jMGd6
            UFpraVBISVRRamw3bFFFZzArSTFZamlvcFdBClZJcU83Q1BNUDlhVmlpbEtzalRH
            ZVhWMTV6MXlVV3hGZGwrTFVnZXo2bVUKLS0tIGJoTmdzNXgzT200TUc4ekduU2Q0
            ODlWRUpWNXlsN1A5dXpGL2JURG1hMkEKCel3tSV0UTgjJnhxMPN5wLHhQtYeJh7f
            eWt/hrrZmDtuGkRyxklgHAE4jy1A1Zp51Wl5u7+Hg6J8vU0hoChrAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2uwxvgqn5c6gx3qlgvj8dg20ev4s4gjgz4gddut6sdy82knvtwdqhdar4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEQyM1dnQSBBdUlEeGd5
            RVVXaFJVcU1XUm5rQVREbEJzVlB3V2FpZy9vVzAyb0dRYjQrTApqRm9YUUl5QzVl
            V0QrcVVHaEoxMnJQbG4zb3JleHZnbHRTV0c5S2JsLytRCi0tLSBkQ1NwTEFtVDNJ
            RkNRdW90N0ZBUGpWTlV2N3pZMHI1ZmFpbkpoUmZlTXRNCmD1WhfRkHTD6RcF+mXP
            eIhjDWzNkTG08PEOiV4hUYaZaRWZPFijAbXM26moBtk2p5meUTA7YdN9LtrdHuxK
            jvc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T22:59:06Z"
    mac: ENC[AES256_GCM,data:bpGqHoEd2qg7eCC/buOee+Metwrgm5DTaLIRfSOnROpOYsdYFc/cGwrnw2y/AnY9jB7ojTEQv6lfJ1wFPP9gcrkUBuZgQTjUApJkF/8lJ7dtfkSrGgrTlRBgIas/ZWMMhr64bCyS3+6xmKEqEMOTW83gqioy8W/t21UM4J9YU3c=,iv:jRK2ZhIRkauk9ezzyKX1IhS7z/ntsQSejdWBvrqxyeY=,tag:QY85OwoQLCMaEicaCoczfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
