---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./downloads-pvc.yaml
  - ../../../shared/templates/flux
  - ./sabnzbd/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./trawl/ks.yaml
  - ./bazarr/ks.yaml
  - ./maintainerr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./jellyseerr-jf/ks.yaml
  - ./pinchflat/ks.yaml
  - ./profilarr/ks.yaml
  - ./qui/ks.yaml
components:
  - ../../../shared/components/kopiur/secret
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: downloads
    unsetOnly: true
