---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nixsmith
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nixsmith-secret
    template:
      data:
        NIXSMITH_JWT_SECRET: "{{ .NIXSMITH_JWT_SECRET }}"
        NIXSMITH_SIGNING_KEY_SEED_BASE64: "{{ .NIXSMITH_SIGNING_KEY_SEED_BASE64 }}"
        NIXSMITH_COOKIE_SIGNING_KEY: "{{ .NIXSMITH_COOKIE_SIGNING_KEY }}"
        NIXSMITH_OIDC_CLIENT_ID: "{{ .NIXSMITH_OAUTH_CLIENT_ID }}"
        NIXSMITH_OIDC_CLIENT_SECRET: "{{ .NIXSMITH_OAUTH_CLIENT_SECRET }}"
        NIXSMITH_GITHUB_APP_ID: "246747"
        NIXSMITH_GITHUB_APP_PRIVATE_KEY: "{{ .BOT_APP_PRIVATE_KEY }}"
        NIXSMITH_WEBHOOK_SECRET_DOTNIX: "{{ .NIXSMITH_WEBHOOK_SECRET_DOTNIX }}"
        NIXSMITH_STORE_AUTH_TOKEN: "{{ .NIXSMITH_STORE_AUTH_TOKEN }}"
  data:
    - secretKey: NIXSMITH_JWT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_JWT_SECRET
    - secretKey: NIXSMITH_SIGNING_KEY_SEED_BASE64
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_SIGNING_KEY_SEED_BASE64
    - secretKey: NIXSMITH_COOKIE_SIGNING_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_COOKIE_SIGNING_KEY
    - secretKey: NIXSMITH_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_OAUTH_CLIENT_ID
    - secretKey: NIXSMITH_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_OAUTH_CLIENT_SECRET
    - secretKey: BOT_APP_PRIVATE_KEY
      remoteRef:
        key: /Github/BOT_APP_PRIVATE_KEY
    - secretKey: NIXSMITH_WEBHOOK_SECRET_DOTNIX
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_WEBHOOK_SECRET_DOTNIX
    - secretKey: NIXSMITH_STORE_AUTH_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Nixsmith/NIXSMITH_STORE_AUTH_TOKEN
