---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: hetzner
  namespace: flux-system
spec:
  suspend: false
  approvePlan: auto
  interval: 12h
  path: ./hetzner
  sourceRef:
    kind: OCIRepository
    name: infrastructure
    namespace: flux-system
  backendConfig:
    disable: true
  tfstate:
    forceUnlock: auto
  cliConfigSecretRef:
    name: tf-controller-tfrc-secret
  runnerPodTemplate:
    spec:
      volumeMounts:
        - name: ssh-key
          mountPath: /home/runner/.ssh/id_ed25519
          subPath: id_ed25519
      volumes:
        - name: ssh-key
          secret:
            secretName: tf-controller-infisical-secret
            defaultMode: 0600
            items:
              - key: SSH_PRIVATE_KEY
                path: id_ed25519
      envFrom:
        - secretRef:
            name: tf-controller-infisical-secret
