---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: hetzner
  namespace: flux-system
spec:
  suspend: false
  approvePlan: auto
  interval: 12h
  path: ./hetzner
  sourceRef:
    kind: OCIRepository
    name: infrastructure
    namespace: flux-system
  backendConfig:
    disable: true
  tfstate:
    forceUnlock: auto
  cliConfigSecretRef:
    name: tf-controller-tfrc-secret
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: tf-controller-infisical-secret
