---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: infrastructure
spec:
  interval: 1m
  ref:
    tag: main
  url: oci://ghcr.io/krezh/manifests/infrastructure
