---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: papra-secret
    template:
      data:
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        AUTH_PROVIDERS_CUSTOMS: |
          [{
            "providerId": "authentik",
            "providerName": "Authentik",
            "clientId": "{{ .PAPRA_OAUTH_CLIENT_ID }}",
            "clientSecret": "{{ .PAPRA_OAUTH_CLIENT_SECRET }}",
            "type": "oidc",
            "discoveryUrl": "https://sso.plexuz.xyz/application/o/papra/.well-known/openid-configuration",
            "scopes": ["openid", "profile", "email", "groups"]
          }]
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Papra/AUTH_SECRET
    - secretKey: PAPRA_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Papra/PAPRA_OAUTH_CLIENT_ID
    - secretKey: PAPRA_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Papra/PAPRA_OAUTH_CLIENT_SECRET
