---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pangolin-operator-secret
    template:
      data:
        PANGOLIN_API_URL: "{{ .PANGOLIN_API_URL }}"
        PANGOLIN_API_KEY: "{{ .PANGOLIN_API_KEY }}"
        PANGOLIN_ENDPOINT: "{{ .PANGOLIN_ENDPOINT }}"
        PANGOLIN_ORG_ID: "{{ .PANGOLIN_ORG_ID }}"
  data:
    - secretKey: PANGOLIN_API_URL
      remoteRef:
        key: /Kubernetes/DexTek/Pangolin/PANGOLIN_API_URL
    - secretKey: PANGOLIN_API_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Pangolin/PANGOLIN_API_KEY
    - secretKey: PANGOLIN_ENDPOINT
      remoteRef:
        key: /Kubernetes/DexTek/Pangolin/PANGOLIN_ENDPOINT
    - secretKey: PANGOLIN_ORG_ID
      remoteRef:
        key: /Kubernetes/DexTek/Pangolin/PANGOLIN_ORG_ID
