---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-sync
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: jellyfin-sync-secret
    template:
      data:
        JELLYFIN_TOKEN: "{{ .JELLYFIN_API_KEY }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        USER_MAPPING: "{{ .JELLYSYNC_USER_MAPPING }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Plex/PLEX_TOKEN
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Jellyfin/JELLYFIN_API_KEY
    - secretKey: JELLYSYNC_USER_MAPPING
      remoteRef:
        key: /Kubernetes/DexTek/Jellyfin/JELLYSYNC_USER_MAPPING
