---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-sync
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: jellyfin-sync-secret
    template:
      data:
        JELLYFIN_TOKEN: "{{ .JELLYFIN_API_KEY }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        USER_MAPPING: "{{ .JELLYSYNC_USER_MAPPING }}"
  dataFrom:
    - find:
        path: /Kubernetes/DexTek/Plex
        name:
          regexp: "(.*)"
    - find:
        path: /Kubernetes/DexTek/Jellyfin
        name:
          regexp: "(.*)"
