---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ../../../shared/templates/flux
  - ./cyberchef/ks.yaml
  - ./redbot/ks.yaml
  - ./home-assistant/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./atuin/ks.yaml
  - ./echo-server/ks.yaml
  - ./mealie/ks.yaml
  - ./it-tools/ks.yaml
  - ./changedetection/ks.yaml
  - ./zipline/ks.yaml
  - ./jellyfin/ks.yaml
  - ./tracearr/ks.yaml
  - ./attic/ks.yaml
  - ./librespeed/ks.yaml
  - ./notifier/ks.yaml
  - ./miniflux/ks.yaml
  - ./termix/ks.yaml
  - ./papra/ks.yaml
  - ./gotify/ks.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: default
    unsetOnly: true
