---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app siren
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: siren
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    controllers:
      siren:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/shamubernetes/siren
              tag: 1.4.30
            env:
              ALERTMANAGER_BASE_URL: http://alertmanager-operated.monitoring.svc.cluster.local:9093
              PORT: &port 3000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /livez
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 200Mi
    service:
      siren:
        controller: siren
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["siren.talos.plexuz.xyz"]
        parentRefs:
          - name: gateway-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
