---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tf-controller-sops
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tf-controller-sops-secret
    template:
      data:
        keys.txt: "{{ .SOPS_KEY }}"
  dataFrom:
    - find:
        path: /Kubernetes/DexTek/TFController
        name:
          regexp: "(.*)"
---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tf-controller-tfrc
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tf-controller-tfrc-secret
    template:
      data:
        terraform.tfrc: |
          credentials "app.terraform.io" {
            token = "{{ .TERRAFORM_CLOUD_TOKEN }}"
          }
  dataFrom:
    - find:
        path: /Kubernetes/DexTek/TFController
        name:
          regexp: "(.*)"
---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tf-controller-infisical
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tf-controller-infisical-secret
    template:
      data:
        INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: "{{ .INFISICAL_ID }}"
        INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: "{{ .INFISICAL_SECRET }}"
        SSH_PRIVATE_KEY: "{{ .SSH_PRIVATEKEY }}"
  dataFrom:
    - find:
        path: /Kubernetes/DexTek/TFController
        name:
          regexp: "(.*)"
    - find:
        path: /Terraform/Hetzner
        name:
          regexp: "(.*)"
