---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  values:
    awsPackage:
      repository: ghcr.io/flux-iac/aws-primitive-modules
      tag: v4.38.0-v1alpha11
    image:
      repository: ghcr.io/flux-iac/tofu-controller
      pullPolicy: IfNotPresent
      tag: v0.16.3
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.11.6@sha256:32d6b02de653d6dfd1073f365b41c07fa48d78eac06613e1e01e372d8a0d552b
    installCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
