---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/nixsmith.io/nixbuilderjobset_v1alpha1.json
apiVersion: nixsmith.io/v1alpha1
kind: NixBuilderJobset
metadata:
  name: dotnix
spec:
  flakeRef: github:krezh/dotnix
  forceRecurse: true
  attrPaths:
    - ci
  pools:
    - amd64-pool
  webhookSecretRef:
    name: nixsmith-secret
    key: NIXSMITH_WEBHOOK_SECRET_DOTNIX
