---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: roder
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: roder-secret
    template:
      data:
        RODER_OIDC_ISSUER_URL: "https://sso.plexuz.xyz/application/o/kubernetes/"
        RODER_OIDC_CLIENT_ID: "{{ .KUBERNETES_OAUTH_CLIENT_ID }}"
        RODER_OIDC_CLIENT_SECRET: "{{ .KUBERNETES_OAUTH_CLIENT_SECRET }}"
        RODER_BASE_URL: "https://roder.plexuz.xyz"
        RODER_SESSION_KEY: "{{ .RODER_SESSION_KEY }}"
  data:
    - secretKey: KUBERNETES_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Kubernetes/KUBERNETES_OAUTH_CLIENT_ID
    - secretKey: KUBERNETES_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Kubernetes/KUBERNETES_OAUTH_CLIENT_SECRET
    - secretKey: RODER_SESSION_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Roder/RODER_SESSION_KEY
