---
# This file is not managed by doco-cd because it can't manage itself

secrets:
  infisical_client_id:
    file: /opt/doco-cd/infisical_client_id
  infisical_client_secret:
    file: /opt/doco-cd/infisical_client_secret
services:
  app:
    container_name: doco-cd
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./docker/vps-attic/
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/krezh/dextek.git
          reference: main
          interval: 3600
      SECRET_PROVIDER: infisical
      SECRET_PROVIDER_SITE_URL: https://eu.infisical.com
      SECRET_PROVIDER_CLIENT_ID_FILE: /run/secrets/infisical_client_id
      SECRET_PROVIDER_CLIENT_SECRET_FILE: /run/secrets/infisical_client_secret
      TZ: Europe/Stockholm
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.76.0@sha256:ef0df49fca5ccaa4c4e01e13bf99d15609c093dd08f53f0c94dacac2a72ed4bd
    restart: unless-stopped
    secrets:
      - infisical_client_id
      - infisical_client_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
