---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: profilarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: profilarr-secret
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Profilarr/PROFILARR_OAUTH_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Profilarr/PROFILARR_OAUTH_CLIENT_SECRET
