---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kaneo-secret
    template:
      data:
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        CUSTOM_OAUTH_CLIENT_ID: "{{ .KANEO_OAUTH_CLIENT_ID }}"
        CUSTOM_OAUTH_CLIENT_SECRET: "{{ .KANEO_OAUTH_CLIENT_SECRET }}"
        CUSTOM_OAUTH_DISCOVERY_URL: https://sso.plexuz.xyz/application/o/kaneo/.well-known/openid-configuration
        CUSTOM_OAUTH_SCOPES: "openid,profile,email"
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Kaneo/AUTH_SECRET
    - secretKey: KANEO_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Kaneo/KANEO_OAUTH_CLIENT_ID
    - secretKey: KANEO_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Kaneo/KANEO_OAUTH_CLIENT_SECRET
