---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${APP}-cnpg-client
spec:
  commonName: ${DB_OWNER:=${APP}}
  usages:
    - client auth
  duration: 720h # 1 month
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  issuerRef:
    name: postgres-client-ca
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: ${APP}-cnpg-client-cert