---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: konflate-secret
  data:
    - secretKey: KONFLATE_WEBHOOK_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Konflate/KONFLATE_WEBHOOK_SECRET
    - secretKey: KONFLATE_APP_CLIENT_ID
      remoteRef:
        key: /Github/BOT_APP_ID
    - secretKey: KONFLATE_APP_PRIVATE_KEY
      remoteRef:
        key: /Github/BOT_APP_PRIVATE_KEY
