doppler:
    token: ENC[AES256_GCM,data:4tBAIm5JTrVTio+tOx81hCRXRC+2P9Xc2FyJnnYo9tPi5EUSWLf0XS2H/4A98dCYGkBXLr93VrfGrjObElA=,iv:8qrRSwZ7GnSbhP1PMuDJp0wMuvNR+V9hFQxBaxJiSqA=,tag:pMXI7H/btsl3hk/lBcm1Lw==,type:str]
sops:
    age:
        - recipient: age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNTd5UmNRRlhPcXZ1Qkpz
            NzhMQjB2UENzVE11NWlibUczUXdZU0VYUHo4CmRXQ25iUzZKN1RISlBBeUlIbURL
            WXZNMWlhcXF3NVVGT3VDSzMwSVJicUEKLS0tIEo4L1lYNjBjeGs0bFI4c0J3dmcy
            Z0FxTUN4L1VNa3NFQUxGekFGWGxHakEKwlETFZXyII1wBstaXnLpwl3VZx7yu6Bb
            BivZ1Xvx1VUcyF5n35iLmPZsJrJZ+8c3y9WK7986O8BLgOdKCtfGHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e7zt8gwt8eg2hcm35h0mlvvexkrxj8uu424lvrmlzvma3ancpvslcevcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSUh5bU9iZXdEZkE1WnhC
            MW9QVVdxNThheHpsOTFnYkJPOXNCOUhQZFF3CkRtdVlhdEMyeHhzVnM4U0duY2VT
            dXd4OHU5THFNbXpwNGoxQjJMSWNVb0EKLS0tICtGTHdWUUxBYUprQnljajh2QjdU
            VDdJY0hlbnpZYUpObUxrS1lrVDNrR2sKat/XmEKPEg3poMTvXe0yO2GP2vw5WgNk
            bqJhe00CpjqsNBgCShEgd2ssRpMGsLbLblMAwp7bfgi8Mc8lZmR+fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2uwxvgqn5c6gx3qlgvj8dg20ev4s4gjgz4gddut6sdy82knvtwdqhdar4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEQyM1dnQSBBam85NUVX
            YXl0Y1R6Uno2RW5QQ3BPeE5lbkJYQUR0QWtzVDUwSEhheWtvaQpUdkdndUJRaTJP
            SlpFM1hZd0lOQk93VmRSUWRiSTZBclBwdWtFMG9BWkM0Ci0tLSBCMmJSRlIrcWlD
            TlNpU0VRU2JaS0tvdTBIWEV3TDk3bUo2Z1JMRi85VmlvCtH3zzFL1VUzIWZPcBYl
            5AaFfoDlBMbK/W178mCYT+YaYKW0pce0RtFx/zhjeXKykIxxs6FcPoWj3L8Jy79C
            UPs=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T22:59:06Z"
    mac: ENC[AES256_GCM,data:im+0aMP30FLsa5F5tLFsdMbZPBbQUGHImJUc4Y72NAq7C0E1wksHALoMQMK2bbBfNOQrnaWeVyNENXO56fFjukDfXIA7R69qeEv0G5slQRtDVKoodt8TsmnQF7yDhxPmZyY1UqL7MT1weNtO+hQRTE9l1lYVCy3XY3oiNTzaGM4=,iv:ggfjg5/Y/2GKO9mdQwUyLj0cYzQ+WqnMbXIhi3lepnw=,tag:nTSiDFHYkKG59TOSMTBmbQ==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.11.0
