---
# yaml-language-server: $schema=https://schemas.vzkn.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app memini
  namespace: flux-system
spec:
  targetNamespace: ai
  dependsOn:
    - name: cnpg-cluster
  path: ./clusters/dextek/apps/ai/memini/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  wait: false
  interval: 1h
  components:
    - ../../../../../shared/components/cnpg/pass
  postBuild:
    substitute:
      APP: *app
      DATABASE_EXTENSIONS: |
        [
          { name: vector },
          { name: vchord }
        ]
