---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ntfy-secret
    template:
      data:
        NTFY_WEB_PUSH_PUBLIC_KEY: "{{ .NTFY_WEB_PUSH_PUBLIC_KEY }}"
        NTFY_WEB_PUSH_PRIVATE_KEY: "{{ .NTFY_WEB_PUSH_PRIVATE_KEY }}"
        NTFY_WEB_PUSH_EMAIL_ADDRESS: "{{ .NTFY_WEB_PUSH_EMAIL_ADDRESS }}"
  data:
    - secretKey: NTFY_WEB_PUSH_PUBLIC_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Ntfy/NTFY_WEB_PUSH_PUBLIC_KEY
    - secretKey: NTFY_WEB_PUSH_PRIVATE_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Ntfy/NTFY_WEB_PUSH_PRIVATE_KEY
    - secretKey: NTFY_WEB_PUSH_EMAIL_ADDRESS
      remoteRef:
        key: /Kubernetes/DexTek/Ntfy/NTFY_WEB_PUSH_EMAIL_ADDRESS
