---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  values:
    fullnameOverride: victoria-logs
    server:
      persistentVolume:
        enabled: true
        storageClassName: ceph-block
        size: 50Gi
      retentionPeriod: 14d
      logLevel: INFO
      route:
        enabled: true
        hostnames:
          - victoria-logs.talos.plexuz.xyz
        parentRefs:
          - name: gateway-internal
            namespace: network
        extraRules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /select/vmui/
                  statusCode: 302
            matches:
              - path:
                  type: Exact
                  value: /
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
