---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-secret
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Grafana/GRAFANA_OAUTH_CLIENT_ID
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Grafana/GRAFANA_OAUTH_CLIENT_SECRET
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: /Kubernetes/DexTek/Grafana/GRAFANA_ADMIN_USER
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: /Kubernetes/DexTek/Grafana/GRAFANA_ADMIN_PASS
