---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hister
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: hister
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      app:
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/asciimoo/hister
              tag: latest
            env:
              HISTER__SERVER__ADDRESS: 0.0.0.0:8080
              HISTER__SERVER__BASE_URL: https://hister.talos.plexuz.xyz
            resources:
              requests:
                cpu: 15m
                memory: 200Mi
              limits:
                memory: 2000Mi
    service:
      app:
        controller: app
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["{{ .Release.Name }}.talos.plexuz.xyz"]
        parentRefs:
          - name: gateway-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: hister-config
        globalMounts:
          - path: /hister/data
