---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tns-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tns-csi-secret
  data:
    - secretKey: url
      remoteRef:
        key: /Kubernetes/DexTek/TNS-CSI/URL
    - secretKey: api-key
      remoteRef:
        key: /Kubernetes/DexTek/TNS-CSI/API_KEY
