cluster:
  etcd:
    advertisedSubnets:
      - 10.10.0.0/27
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: dextek
endpoint: https://192.168.25.20:6443
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
  - os:reader
allowedKubernetesNamespaces:
  - kube-system
  - ai
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  feature-gates: PersistentVolumeClaimUnusedSinceTime=true,HPAScaleToZero=true
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeAdmissionControlConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
certExtraSANs:
  - 192.168.25.20
  - dextek.plexuz.xyz
  - 127.0.0.1
  - localhost
extraArgs:
  enable-aggregator-routing: "true"
  feature-gates: PersistentVolumeClaimUnusedSinceTime=true,HPAScaleToZero=true
  default-not-ready-toleration-seconds: "60"
  default-unreachable-toleration-seconds: "60"
---
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  jwt:
    - issuer:
        url: https://sso.plexuz.xyz/application/o/kubernetes/
        audiences:
          - kubernetes
      claimMappings:
        username:
          claim: email
          prefix: ""
        groups:
          claim: groups
          prefix: ""
---
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
config:
  profiles:
    - schedulerName: default-scheduler
      plugins:
        score:
          disabled:
            - name: ImageLocality
      pluginConfig:
        - name: PodTopologySpread
          args:
            defaultingType: List
            defaultConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
