---
working_dir: ./docker/vps-pangolin
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  MAXMIND_ACCOUNT_ID: 5e13949c-f810-489d-88bd-0749b9474dbb:default:/Docker/Pangolin/MAXMIND_ACCOUNT_ID
  MAXMIND_LICENSE_KEY: 5e13949c-f810-489d-88bd-0749b9474dbb:default:/Docker/Pangolin/MAXMIND_LICENSE_KEY
  PANGOLIN_SERVER_SECRET: 5e13949c-f810-489d-88bd-0749b9474dbb:default:/Docker/Pangolin/PANGOLIN_SERVER_SECRET
  CF_DNS_API_TOKEN: 5e13949c-f810-489d-88bd-0749b9474dbb:default:/Docker/Pangolin/CF_DNS_API_TOKEN
