#!/usr/bin/env just --justfile

set quiet := true
set ignore-comments := true

_default:
    @just --list

[no-cd]
init:
    tofu init --upgrade

[no-cd]
apply: init
    tofu apply --auto-approve

[no-cd]
plan: init
    tofu plan

[no-cd]
force-unlock:
    tofu force-unlock "krezh/$(basename $(pwd -P))"
