#!/usr/bin/env just --justfile

set quiet
set ignore-comments

_default:
  @just --list

[no-cd]
init:
	tofu init --upgrade

[no-cd]
apply: init
  tofu apply --auto-approve

[no-cd]
plan: init
  tofu plan

