#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

_default:
  @just --list

[no-cd]
init:
	@tofu init --upgrade

[no-cd]
apply: init
  @tofu apply --auto-approve

[no-cd]
plan: init
  @tofu plan

