---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: niks3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: niks3-secret
  data:
    - secretKey: NIKS3_API_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Niks3/NIKS3_API_TOKEN
    - secretKey: NIKS3_S3_ACCESS_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Niks3/NIKS3_S3_ACCESS_KEY
    - secretKey: NIKS3_S3_SECRET_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Niks3/NIKS3_S3_SECRET_KEY
    - secretKey: NIKS3_S3_ENDPOINT
      remoteRef:
        key: /Kubernetes/DexTek/Niks3/NIKS3_S3_ENDPOINT
