---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app niks3
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: niks3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      app:
        type: deployment
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mic92/niks3
              tag: v1.7.0
            env:
              NIKS3_DB:
                valueFrom:
                  secretKeyRef:
                    name: niks3-postgres
                    key: url
              NIKS3_HTTP_ADDR: :5751
              NIKS3_CACHE_URL: https://niks.plexuz.xyz
              NIKS3_S3_BUCKET: niks3
              NIKS3_S3_REGION: auto
              NIKS3_SIGN_KEY_PATHS: /etc/niks3/signing.key
              NIKS3_OIDC_CONFIG: /etc/niks3/oidc.json
            envFrom:
              - secretRef:
                  name: niks3-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 5751
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64M
              limits:
                memory: 2500M
    service:
      app:
        controller: app
        ports:
          http:
            port: *port
    route:
      external:
        hostnames: ["niks.plexuz.xyz"]
        parentRefs:
          - name: gateway-external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      signing-key:
        type: secret
        name: niks3-secret
        globalMounts:
          - path: /etc/niks3/signing.key
            subPath: signing.key
            readOnly: true
      oidc-config:
        type: configMap
        name: niks3-oidc
        globalMounts:
          - path: /etc/niks3/oidc.json
            subPath: oidc.json
            readOnly: true
