---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ../../../shared/templates/flux
  - ./ingress-nginx/ks.yaml
  - ./cloudflare-dns/ks.yaml
  - ./unifi-dns/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./multus/ks.yaml
  - ./towonel-agent/ks.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: network
    unsetOnly: true
