---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: context7
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: context7-secret
  data:
    - secretKey: CONTEXT7_API_KEY
      remoteRef:
        key: /Kubernetes/DexTek/MCP/CONTEXT7_API_KEY
