---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app text-embeddings-inference
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/dextek/apps/ai/text-embeddings-inference/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
