---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-mcp-secret
  data:
    - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/MCP/GRAFANA_SERVICE_ACCOUNT_TOKEN
