---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: zipline-secret
    template:
      data:
        OAUTH_AUTHENTIK_AUTHORIZE_URL: https://sso.plexuz.xyz/application/o/authorize/
        OAUTH_AUTHENTIK_USERINFO_URL: https://sso.plexuz.xyz/application/o/userinfo/
        OAUTH_AUTHENTIK_TOKEN_URL: https://sso.plexuz.xyz/application/o/token/
  data:
    - secretKey: CORE_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Zipline/ZIPLINE_CORE_SECRET
    - secretKey: OAUTH_AUTHENTIK_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Zipline/ZIPLINE_OAUTH_CLIENT_ID
    - secretKey: OAUTH_AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Zipline/ZIPLINE_OAUTH_CLIENT_SECRET
---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline-postgres
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: zipline-postgres-secret
    template:
      data:
        DATABASE_URL: '{{ index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-zipline
