---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../shared/templates/flux
  - ./namespace.yaml
  - ./toolhive/ks.yaml
  - ./memini/ks.yaml
  - ./context7-mcp/ks.yaml
  - ./github-mcp/ks.yaml
  - ./grafana-mcp/ks.yaml
  - ./sidero-mcp/ks.yaml
  - ./talos-mcp/ks.yaml
  - ./nixos-mcp/ks.yaml
  - ./llmkube/ks.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: ai
    unsetOnly: true
