---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulumi-talos
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pulumi-talos-secret
    template:
      data:
        PULUMI_ACCESS_TOKEN: "{{ .PULUMI_ACCESS_TOKEN }}"
        INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: "{{ .INFISICAL_ID }}"
        INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: "{{ .INFISICAL_SECRET }}"
  data:
    - secretKey: PULUMI_ACCESS_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Pulumi/PULUMI_ACCESS_TOKEN
    - secretKey: INFISICAL_ID
      remoteRef:
        key: /Kubernetes/DexTek/TFController/INFISICAL_ID
    - secretKey: INFISICAL_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/TFController/INFISICAL_SECRET
