---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gotify
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-operator-cluster
    - name: crunchy-postgres-stores
    - name: external-secrets-stores
  path: ./clusters/dextek/apps/default/gotify/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  components:
    - ../../../../../shared/components/volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_CLAIM: *app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gotify-icons
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: gotify
  path: ./clusters/dextek/apps/default/gotify/icons
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
