---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-signing-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: forgejo-signing-key
  data:
    - secretKey: ed25519
      remoteRef:
        key: /Kubernetes/DexTek/Forgejo/SIGNING_PRIVATE_KEY
    - secretKey: ed25519.pub
      remoteRef:
        key: /Kubernetes/DexTek/Forgejo/SIGNING_PUBLIC_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-authentik-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: forgejo-authentik-oidc
  data:
    - secretKey: key
      remoteRef:
        key: /Kubernetes/DexTek/Forgejo/FORGEJO_OAUTH_CLIENT_ID
    - secretKey: secret
      remoteRef:
        key: /Kubernetes/DexTek/Forgejo/FORGEJO_OAUTH_CLIENT_SECRET
