---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: barman-garage
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        GARAGE_ACCESS_KEY_ID: "{{ .GARAGE_ACCESS_KEY_ID }}"
        GARAGE_SECRET_ACCESS_KEY: "{{ .GARAGE_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: GARAGE_ACCESS_KEY_ID
      remoteRef:
        key: /Kubernetes/DexTek/CNPG/GARAGE_ACCESS_KEY_ID
    - secretKey: GARAGE_SECRET_ACCESS_KEY
      remoteRef:
        key: /Kubernetes/DexTek/CNPG/GARAGE_SECRET_ACCESS_KEY
