---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
spec:
  configuration:
    destinationPath: s3://cnpg/
    endpointURL: https://s3.fast.plexuz.xyz
    s3Credentials:
      accessKeyId:
        name: barman-garage
        key: GARAGE_ACCESS_KEY_ID
      secretAccessKey:
        name: barman-garage
        key: GARAGE_SECRET_ACCESS_KEY
    wal:
      compression: zstd
    data:
      compression: bzip2
  retentionPolicy: "14d"
