---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/pooler_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgres
  instances: 2
  type: rw
  serviceTemplate:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: pgbouncer-cnpg.plexuz.xyz
    spec:
      type: LoadBalancer
  pgbouncer:
    poolMode: session
    authQuery: "SELECT $1, NULL"
    serverCASecret:
      name: pooler-server-cert
    serverTLSSecret:
      name: pooler-client-cert
    clientCASecret:
      name: postgres-client-ca
    clientTLSSecret:
      name: pooler-server-cert
    parameters:
      auth_type: cert
      server_tls_sslmode: verify-full
      client_tls_sslmode: verify-full
      max_client_conn: "500"
      max_prepared_statements: "200"
      default_pool_size: "100"
      ignore_startup_parameters: search_path,options
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name pooler-rw
spec:
  selector:
    matchLabels:
      cnpg.io/poolerName: *name
  podMetricsEndpoints:
    - port: metrics
