---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: coder-secret
    template:
      data:
        CODER_OIDC_CLIENT_ID: "{{ .CODER_OIDC_CLIENT_ID }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .CODER_OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: CODER_OIDC_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Coder/CODER_OAUTH_CLIENT_ID
    - secretKey: CODER_OIDC_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Coder/CODER_OAUTH_CLIENT_SECRET
