---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: downloads
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: radarr
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      app:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.1.2.10359@sha256:9967e56263a3c67eeaede5824103ee4c1c1f1511abd5965ac1e294bfd9b76dbb
            env:
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__SERVER__PORT: &port 7878
              RADARR__AUTHENTICATION_METHOD: External
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__UPDATE__BRANCH: develop
            envFrom: &envFrom
              - secretRef:
                  name: radarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              limits:
                memory: 2000Mi
          anubis:
            image:
              repository: ghcr.io/techarohq/anubis
              tag: latest
            env:
              # https://anubis.techaro.lol/docs/admin/installation#environment-variables
              BIND: ":8080"
              COOKIE_DOMAIN: plexuz.xyz
              BIND_NETWORK: tcp
              DIFFICULTY: "5"
              METRICS_BIND: ":9090"
              METRICS_BIND_NETWORK: tcp
              SERVE_ROBOTS_TXT: "true"
              TARGET: http://localhost:7878
              OG_PASSTHROUGH: "true"
              OG_EXPIRY_TIME: 24h
              CUSTOM_REAL_IP_HEADER: Cf-Connecting-Ip
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 12Mi
    service:
      app:
        controller: app
        ports:
          http:
            port: 80
            targetPort: *port
          anubis:
            port: 8080
    route:
      app:
        hostnames: ["{{ .Release.Name }}.plexuz.xyz"]
        parentRefs:
          - name: gateway-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
      api:
        hostnames: ["{{ .Release.Name }}.plexuz.xyz"]
        annotations:
          gatus.home-operations.com/endpoint: |-
            url: https://{{ .Release.Name }}.plexuz.xyz/ping
        parentRefs:
          - name: gateway-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
            matches:
              - path:
                  type: PathPrefix
                  value: /api
              - path:
                  type: PathPrefix
                  value: /ping
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        type: nfs
        server: jotunheim.fast.internal
        path: /mnt/tank/media
        globalMounts:
          - path: /media
      downloads:
        enabled: true
        existingClaim: downloads
