---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: chaski-secret
  data:
    - secretKey: RADARR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Radarr/GOTIFY_TOKEN
    - secretKey: SEERR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Jellyseerr/GOTIFY_TOKEN
    - secretKey: SONARR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Sonarr/GOTIFY_TOKEN
    - secretKey: ALERTMANAGER_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/AlertManager/GOTIFY_TOKEN
    - secretKey: PROFILARR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Profilarr/GOTIFY_TOKEN
    - secretKey: PROWLARR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Prowlarr/GOTIFY_TOKEN
