---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: chaski-secret
    template:
      data:
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        RADARR_PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        SEERR_PUSHOVER_TOKEN: "{{ .SEERR_PUSHOVER_TOKEN }}"
        SONARR_PUSHOVER_TOKEN: "{{ .SONARR_PUSHOVER_TOKEN }}"
        RADARR_GOTIFY_TOKEN: "{{ .RADARR_GOTIFY_TOKEN }}"
        SEERR_GOTIFY_TOKEN: "{{ .SEERR_GOTIFY_TOKEN }}"
        SONARR_GOTIFY_TOKEN: "{{ .SONARR_GOTIFY_TOKEN }}"
        ALERTMANAGER_GOTIFY_TOKEN: "{{ .ALERTMANAGER_GOTIFY_TOKEN }}"
  data:
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Pushover/PUSHOVER_USER_KEY
    - secretKey: RADARR_PUSHOVER_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Radarr/RADARR_PUSHOVER_TOKEN
    - secretKey: SEERR_PUSHOVER_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Jellyseerr/SEERR_PUSHOVER_TOKEN
    - secretKey: SONARR_PUSHOVER_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Sonarr/SONARR_PUSHOVER_TOKEN
    - secretKey: RADARR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Radarr/GOTIFY_TOKEN
    - secretKey: SEERR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Jellyseerr/GOTIFY_TOKEN
    - secretKey: SONARR_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Sonarr/GOTIFY_TOKEN
    - secretKey: ALERTMANAGER_GOTIFY_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/AlertManager/GOTIFY_TOKEN
