apiVersion: v1
kind: Secret
metadata:
    name: infisical-auth
stringData:
    clientId: ENC[AES256_GCM,data:VXOyQo51o1oHgCkzTW82dQAF4PMmzqkMtXVoOvXP9QLhXdzE,iv:Boxxgh2YhwAHV2RZPyMXF4VAc9H44Dko5+E42/lxat0=,tag:1lgZajYAUvkooHJNBD6LVw==,type:str]
    clientSecret: ENC[AES256_GCM,data:QNfg3Iui8eX2jTh8OmWNoXHEmma1L8550BlaSvWLJKacZjtcNZeFkANTJp5Lt7cAkqe12sWYlHi4gfdrFbSAdg==,iv:clUpFSFb8O7ZnnjX9ctyGOwzKR3Kgwo/TjyO68Z94yw=,tag:oBWOPd8ukOO/7pye9jcNgQ==,type:str]
sops:
    age:
        - recipient: age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONGtyVElrR2JVLzdNeE9L
            bUNUSmlOdUJVd05rSzBKMjFrRi8rTEt5NUd3ClhYUHF2WEFQRlVObU9vOUlZR0hK
            cEZZbEl0K2hSL1FnOFc5ajdRam5IWGcKLS0tICsweVJTK3Y3aGExSnpJQWpqQ24y
            Yk9CM2U3czJPZzBQVzI0VE84elBQcEkKSgZGmQ5JEDixMB96g4g+a8b+4ZQiAogO
            II53jQy9kK3kMWDqf0PxZC614SjS6qBsQPBFBN3nJFrCLTBqdVG/pA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e7zt8gwt8eg2hcm35h0mlvvexkrxj8uu424lvrmlzvma3ancpvslcevcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZm9JczlTS0xIRjdsRlN1
            VEZJbDV1VTZuTUZ2Zlo3ZFYwZ1JJb1BUaWxFCk9MNVRyYkpXRURPL1ZOUkdqTkM2
            SG5oanpNTjhpRExNRHRKd0dMY0hickEKLS0tIExBUU1JaWgwOERhZEI0VENlV1Zu
            bGdlUW05QjkyczlGbHB5MGtvQVp1bncK8Vf5mMUk2Up9K50MbNxO1tnDkMRzn5bc
            YQHzwl9HQQuP524TKo3E4UlCVNGhm2dIyeYZCWLae2++KedlVk9vrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2uwxvgqn5c6gx3qlgvj8dg20ev4s4gjgz4gddut6sdy82knvtwdqhdar4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEQyM1dnQSBBM0ViYW9u
            YzJIa0lLeHlpRUZlMkpISXE2RnYyWTVVZVJsWVRhTDdQNnl5WQpyZ085ejF6NHZC
            aXA1UWZGd2tDQTVwblNTVDBtUFpUM1RuYXdCY3h1M2dzCi0tLSBqVVhZODZtazBC
            UW9EQXBZaFVuK3pTV3ltUjcxdWxYMkdSQWFUQitOZVhrCqK1m6iEMYcHJwPqfRwT
            zGdiqpW2vmEoE/8m3fsqvw34OwIzhXg/GdehsGe3JK7hcJkhyZ7MW917FNLj7hKG
            Xbo=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T22:59:06Z"
    mac: ENC[AES256_GCM,data:f+ug0l8dG72wNDAS1w12oM2c92Cy81fAwvwaTZSKETo/2dKJcURONXgSMUiNk11XxcbJNLvLxC2PBFHCEOGa16MrvJuNwhxSxkP7Ihpdj/vhkISmPx3NwM3bfUZVXtXs+K6eUvoEh8dV9tJ+zRSpnE3Ahwhav2fuvSuMzl5sVro=,iv:mFSOsuSmn5/2nf/1FRQZre+BBCk1mHVOBjSKxM/04MY=,tag:6VJFH46cGu0Im2xuB4wPUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
