---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/postgres-operator.crunchydata.com/pgupgrade_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: postgres-upgrade
  namespace: databases
spec:
  image: ghcr.io/krezh/cdpg-vchord-18-upgrade:18.3.2610@sha256:3d84404a06f09bf83c21ae7537209bc32a34bd6cca0553897ae7cd0c0d0b827e
  postgresClusterName: postgres
  fromPostgresVersion: 16
  toPostgresVersion: 18
