---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/postgres-operator.crunchydata.com/pgupgrade_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: postgres-upgrade
  namespace: databases
spec:
  image: ghcr.io/krezh/cdpg-vchord-18-upgrade:18.3.2610@sha256:90a040527e2f8c159729b5c86841b67a167f790f1ff65ec4d56a78e98b5988a8
  postgresClusterName: postgres
  fromPostgresVersion: 16
  toPostgresVersion: 18
