---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cyberchef
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cyberchef
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      app:
        type: deployment
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/mpepping/cyberchef
              tag: v11.4.0@sha256:a004ba65ac2cb4d7bfcea65a85d19208dae643b661ea9bfd21247073b61f2c93
            resources:
              requests:
                cpu: 15m
                memory: 27M
              limits:
                memory: 105M
    service:
      app:
        controller: app
        ports:
          http:
            port: &port 8000
    route:
      app:
        hostnames: ["chef.plexuz.xyz"]
        parentRefs:
          - name: gateway-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
