{
 "title": "NUT UPS",
 "description": "Dashboard for HON95's Prometheus NUT Exporter.",
 "tags": [ "UPS" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "nut_ups_info" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Watts",
   "type": "stat",
   "description": "Power usage in watts",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ups) (nut_real_power_watts{ups=~\"${ups}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage_volts{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_beeper_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(ups) (100 * avg_over_time(nut_battery_charge{ups=~\"${ups}\"}[$__interval]))",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(ups) (avg_over_time(nut_battery_runtime_seconds{ups=~\"${ups}\"}[$__interval]))",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(ups) (avg_over_time(nut_load{ups=~\"${ups}\"}[$__interval]))",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "sum by(ups) (avg_over_time(nut_battery_voltage_volts{ups=~\"${ups}\"}[$__interval]))",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "sum by(ups) (avg_over_time(nut_input_voltage_volts{ups=~\"${ups}\"}[$__interval]))",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "sum by(ups) (avg_over_time(nut_output_voltage_volts{ups=~\"${ups}\"}[$__interval]))",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Watt History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(nut_real_power_watts{$ups=\"$ups\"}) by (ups)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}