---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: renovate-secret
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Renovate/CODEBERG_TOKEN
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Renovate/GITHUB_TOKEN
