---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: renovate-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_APP_ID: "246747"
        INSTALL_ID: "30141337"
        private-key.pem: "{{ .BOT_APP_PRIVATE_KEY }}"
        OPERATOR_WEBHOOK_KEY: "{{ .OPERATOR_WEBHOOK_KEY }}"
  data:
    - secretKey: BOT_APP_PRIVATE_KEY
      remoteRef:
        key: /Github/BOT_APP_PRIVATE_KEY
    - secretKey: OPERATOR_WEBHOOK_KEY
      remoteRef:
        key: /Kubernetes/DexTek/Renovate/OPERATOR_WEBHOOK_KEY
