---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "246747"
  installID: "28595968"
  auth:
    privateKey:
      secretRef:
        name: github-app-pem
        key: private_key_pem
