---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: default
spec:
  image: ghcr.io/renovatebot/renovate:43.170.16
  discoverTopics:
    - renovate-default
  discoveryFilters:
    - dextek/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_GIT_AUTHOR
      value: dextek-bot <dextek-bot@noreply.codeberg.org>
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.databases.svc:6379/3"
  parallelism: 10
  schedule: 0 * * * *
  provider:
    name: forgejo
    endpoint: https://codeberg.org
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: &secret renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: *secret
        key: OPERATOR_WEBHOOK_KEY
    forgejo:
      sync:
        enabled: false
        webhookURL: https://renovate-webhook.plexuz.xyz/webhook/v1/forgejo
        tokenSecretRef:
          name: *secret
          key: RENOVATE_TOKEN
        authTokenSecretRef:
          name: *secret
          key: OPERATOR_WEBHOOK_KEY
