---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github
spec:
  image: ghcr.io/krezh/renovate-nix:43.227.0@sha256:8e98af472fb1bec0bfdc0dd36338881b4513c3d6c479f3582d7ae9e410a3289d
  discoverTopics:
    - renovate
  discoveryFilters:
    - krezh/*
  extraEnv:
    - name: NIX_CONFIG
      value: "access-tokens = github.com=$(RENOVATE_TOKEN)"
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ONBOARDING_CONFIG_FILE_NAME
      value: .renovaterc.json5
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.databases.svc:6379/3"
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |
        [
          "^nix run github:purpleclay/go-overlay#govendor",
          "^bash .github/scripts/update-hash.sh",
        ]
  parallelism: 10
  schedule: 0 * * * *
  provider:
    name: github
  githubAppReference:
    secretName: renovate-secret
    appIdSecretKey: GITHUB_APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: private-key.pem
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: &secret renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: *secret
        key: OPERATOR_WEBHOOK_KEY
