---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: nix
spec:
  image: ghcr.io/krezh/renovate-nix:43.197.0@sha256:7d17ba2ecd635f2fb93dd6282755d59f6e7a1f52cd5d9f90ba33417ba6043c18
  discoverTopics:
    - renovate-nix
  discoveryFilters:
    - krezh/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.databases.svc:6379/3"
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        [
          "^bash -c 'PKG=\\$\\(grep",
          "^nix run github:Mic92/nix-update",
          "^nix run github:nix-community/gomod2nix",
          "^nix run github:purpleclay/go-overlay#govendor",
          "^bash .forgejo/scripts/update-hash.sh",
        ]
  parallelism: 10
  schedule: 0 * * * *
  provider:
    name: github
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: &secret renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: *secret
        key: OPERATOR_WEBHOOK_KEY
