---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: nix
spec:
  image: ghcr.io/krezh/renovate-nix:43.160.5@sha256:8252946e04e4acd51205e46501c362688b83eb4256d7a634738709079e58adaa
  discoverTopics:
    - renovate-nix
  discoveryFilters:
    - dextek/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_GIT_AUTHOR
      value: dextek-bot <dextek-bot@noreply.codeberg.org>
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        [
          "^bash -c 'PKG=\\$\\(grep",
          "^nix run github:Mic92/nix-update",
          "^nix run github:nix-community/gomod2nix",
          "^nix run github:purpleclay/go-overlay#govendor",
          "^bash .forgejo/scripts/update-hash.sh",
        ]
  parallelism: 10
  schedule: 0 * * * *
  provider:
    name: forgejo
    endpoint: https://codeberg.org
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: &secret renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: *secret
        key: OPERATOR_WEBHOOK_KEY
    forgejo:
      sync:
        enabled: true
        webhookURL: https://renovate-webhook.plexuz.xyz/webhook/v1/forgejo
        topic: renovate-nix
        tokenSecretRef:
          name: *secret
          key: RENOVATE_TOKEN
        authTokenSecretRef:
          name: *secret
          key: OPERATOR_WEBHOOK_KEY
