---
http:
  middlewares:
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
    badger:
      plugin:
        badger:
          disableForwardAuth: true
    redirect-to-https:
      redirectScheme:
        scheme: https
    security-headers:
      headers:
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customResponseHeaders:
          Server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: strict-origin-when-cross-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
  routers:
    main-app-router-redirect:
      rule: "Host(`pangolin.plexuz.xyz`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
        - badger
    next-router:
      rule: "Host(`pangolin.plexuz.xyz`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      middlewares:
        - badger
      tls:
        certResolver: letsencrypt
        domains:
          - main: "plexuz.xyz"
            sans:
              - "*.plexuz.xyz"
    api-router:
      rule: "Host(`pangolin.plexuz.xyz`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      middlewares:
        - badger
      tls:
        certResolver: letsencrypt
    int-api-router:
      rule: "Host(`pangolin-api.plexuz.xyz`)"
      service: int-api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    ws-router:
      rule: "Host(`pangolin.plexuz.xyz`)"
      service: api-service
      entryPoints:
        - websecure
      middlewares:
        - badger
      tls:
        certResolver: letsencrypt
    doco-cd-redirect:
      rule: "Host(`pangolin-doco.plexuz.xyz`)"
      service: doco-cd-svc
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
    doco-cd-router:
      rule: "Host(`pangolin-doco.plexuz.xyz`)"
      service: doco-cd-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"
    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"
    int-api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3003"
    doco-cd-svc:
      loadBalancer:
        servers:
          - url: "http://doco-cd:8880"
