---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: ${APP}-postgres
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
  labels:
    postgresql.cnpg.io/role: "true"
spec:
  type: Static
  defaultValues:
    role: ${DB_OWNER:=${APP}}
    app: ${APP}
    disablePassword: ${DISABLE_PASSWORD:=true}
    superuser: ${DATABASE_SUPERUSER:=false}
