---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: attic
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: attic-secret
    template:
      data:
        ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: "{{ .ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64 }}"
        ATTIC_SERVER_DATABASE_URL: '{{ index . "uri" }}'
        AWS_ACCESS_KEY_ID: "{{ .ATTIC_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .ATTIC_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - find:
        path: /Kubernetes/DexTek/Attic
        name:
          regexp: "(.*)"
    - extract:
        key: postgres-pguser-attic
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
