---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  route:
    groupBy: [ "alertname", "job" ]
    groupInterval: 10m
    groupWait: 1m
    receiver: gotify
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: "InfoInhibitor|Watchdog"
            matchType: =~
      - receiver: gotify
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal: [ "alertname", "namespace" ]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: gotify
      webhookConfigs:
        - url: http://notifier.default.svc.cluster.local/hooks/alertmanager-gotify
          sendResolved: true
