---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ${OIDC_CLIENT_SECRET_NAME:-${APP}-oidc-secret}
    template:
      data:
        client-secret: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/${OIDC_INFISICAL_FOLDER}/OIDC_CLIENT_SECRET
