---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Flux Image Test"

on:
  pull_request:
    branches: ["main"]
    paths: ["clusters/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  changed-clusters:
    name: Changed Clusters
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.changed-clusters.outputs.changed_files }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: "${{ steps.app-token.outputs.token }}"
          persist-credentials: false
          fetch-depth: 0

      - name: Get Changed Clusters
        id: changed-clusters
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: clusters/!(shared)/**
          include_only_directories: true
          max_depth: 2

      - name: List All Changed Clusters
        env:
          CHANGED_FILES: ${{ steps.changed-clusters.outputs.changed_files }}
        run: echo "$CHANGED_FILES"

  extract-images:
    name: Extract Images
    runs-on: ubuntu-latest
    needs: ["changed-clusters"]
    environment: prod
    permissions:
      pull-requests: write
    strategy:
      matrix:
        paths: ${{ fromJSON(needs.changed-clusters.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    outputs:
      matrix: ${{ steps.extract-images.outputs.images }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup yq
        uses: mikefarah/yq@751d8ad57b84f1794661bc70c0afb92a22ad7b3c # v4.53.2
        with:
          cmd: yq --version

      - name: Setup jo
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y jo

      - name: Checkout Default Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: "${{ steps.app-token.outputs.token }}"
          persist-credentials: false
          ref: "${{ github.event.repository.default_branch }}"
          path: default

      - name: Checkout Pull Request Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: "${{ steps.app-token.outputs.token }}"
          persist-credentials: false
          path: pull

      - name: Gather Images in Default Branch
        uses: docker://ghcr.io/allenporter/flux-local:v8.2
        with:
          args: >-
            get cluster
            --path /github/workspace/default/${{ matrix.paths }}/flux
            --enable-images
            --output yaml
            --output-file default.yaml

      - name: Gather Images in Pull Request Branch
        uses: docker://ghcr.io/allenporter/flux-local:v8.2
        with:
          args: >-
            get cluster
            --path /github/workspace/pull/${{ matrix.paths }}/flux
            --enable-images
            --output yaml
            --output-file pull.yaml

      - name: Filter Default Branch Results
        shell: bash
        run: |
          yq -r '[.. | .images? | select(. != null)] | flatten | sort | unique | .[]' \
              default.yaml > default.txt

      - name: Filter Pull Request Branch Results
        shell: bash
        run: |
          yq -r '[.. | .images? | select(. != null)] | flatten | sort | unique | .[]' \
              pull.yaml > pull.txt

      - name: Compare Default and Pull Request Images
        id: extract-images
        shell: bash
        run: |
          images=$(jo -a $(grep -vf default.txt pull.txt))
          echo "images=${images}" >> $GITHUB_OUTPUT
          echo "${images}"
          echo "### Images" >> $GITHUB_STEP_SUMMARY
          echo "${images}" | jq -r 'to_entries[] | "* \(.value)"' >> $GITHUB_STEP_SUMMARY

  test-images:
    if: ${{ needs.extract-images.outputs.matrix != '[]' }}
    name: Test images
    runs-on: ubuntu-latest
    needs: ["extract-images"]
    permissions: {}
    strategy:
      matrix:
        images: ${{ fromJSON(needs.extract-images.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Inspect Image
        env:
          IMAGE: ${{ matrix.images }}
        run: docker buildx imagetools inspect "$IMAGE"

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  test-images-success:
    if: ${{ always() }}
    needs: ["test-images"]
    name: Test Images Successful
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        name: Check matrix status
        run: exit 1
