---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../shared/templates/flux
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./kromgo/ks.yaml
  - ./alloy/ks.yaml
  - ./silence-operator/ks.yaml
  - ./gatus/ks.yaml
  - ./prometheus-adapter/ks.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: monitoring
    unsetOnly: true
