---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: noctune
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: noctune-secret
    template:
      data:
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        SPOTIFY_CLIENT_ID: "{{ .SPOTIFY_CLIENT_ID }}"
        SPOTIFY_CLIENT_SECRET: "{{ .SPOTIFY_CLIENT_SECRET }}"
        DISCORD_CLIENT_ID: "{{ .DISCORD_CLIENT_ID }}"
        DISCORD_CLIENT_SECRET: "{{ .DISCORD_CLIENT_SECRET }}"
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: /Kubernetes/DexTek/Noctune/DISCORD_BOT_TOKEN
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Noctune/SPOTIFY_CLIENT_ID
    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Noctune/SPOTIFY_CLIENT_SECRET
    - secretKey: DISCORD_CLIENT_ID
      remoteRef:
        key: /Kubernetes/DexTek/Noctune/DISCORD_CLIENT_ID
    - secretKey: DISCORD_CLIENT_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Noctune/DISCORD_CLIENT_SECRET
    - secretKey: SESSION_SECRET
      remoteRef:
        key: /Kubernetes/DexTek/Noctune/SESSION_SECRET
