---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: noctune
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: noctune
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/krezh/noctune
              tag: 0.1.4@sha256:4638607b1e18ef3b6980a58707c127206f5bd815ca4f46da969080e01f524fb1
            env:
              WEB_LISTEN_ADDR: ":8080"
              WEB_PUBLIC_URL: "https://alfred.plexuz.xyz"
              CACHE_DIR: /data/cache
            envFrom:
              - secretRef:
                  name: noctune-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "alfred.plexuz.xyz"
        parentRefs:
          - name: gateway-external
            namespace: network
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /data/cache
