---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
  # https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml
  values:
    fullnameOverride: alloy
    serviceMonitor:
      enabled: true
    controller:
      extraAnnotations:
        reloader.stakater.com/auto: "true"
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: syslog.talos.plexuz.xyz
      externalTrafficPolicy: Local
    alloy:
      enableReporting: false
      clustering:
        enabled: true
      extraPorts:
        - name: syslog-udp
          port: 1514
          targetPort: 1514
          protocol: UDP
      configMap:
        create: false
        name: alloy-configmap
        key: config.alloy
    ingress:
      enabled: false
