---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
resources:
  - ./resourceclaimtemplate.yaml
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          defaultPodOptions:
            securityContext:
              supplementalGroups: [44]
            resourceClaims:
              - name: gpu
                resourceClaimTemplateName: ${APP}-gpu
